export const RECEIVE_PHONES_LIST = "RECEIVE_PHONES_LIST";
export const CLEAR_PHONES_LIST = "CLEAR_PHONES_LIST";
export const RECEIVE_FILTERS_LIST = "RECEIVE_FILTERS_LIST";
export const CHECK_FILTER = "CHECK_FILTER";
export const UNCHECK_FILTER = "UNCHECK_FILTER";
export const RANGE_CHANGED = "RANGE_CHANGED";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const PHONES_CHANGE_PAGE = "PHONES_CHANGE_PAGE";

export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const RECEIVE_AVATAR = "RECEIVE_AVATAR";
export const RECEIVE_ORDERS = "RECEIVE_ORDERS";

export const UPDATE_SEARCH_STRING = "UPDATE_SEARCH_STRING";
export const UPDATE_SEARCH_LIST = "UPDATE_SEARCH_LIST";

export const RECEIVE_PHONE_DETAIL = "RECEIVE_PHONE_DETAIL";

export const RECEIVE_CART = "RECEIVE_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_CART = "CLEAR_CART";

export const ADMIN_CLEAR_PHONES_LIST = "ADMIN_CLEAR_PHONES_LIST";
export const ADMIN_RECEIVE_PHONES_LIST = "ADMIN_RECEIVE_PHONES_LIST";
export const ADMIN_CHANGE_PHONES_LIST = "ADMIN_CHANGE_PHONES_LIST";
export const ADMIN_INCREMENT_PHONES_LIST = "ADMIN_INCREMENT_PHONES_LIST";
export const ADMIN_RECEIVE_USERS_LIST = "ADMIN_RECEIVE_USERS_LIST";
export const ADMIN_CLEAR_USERS_LIST = "ADMIN_CLEAR_USERS_LIST";

export const RECEIVE_FORM_DATA = "RECEIVE_FORM_DATA";